# Generated by Django 5.2 on 2025-09-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='menuitem',
            name='unique_menuitem_category_name',
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='unique_orderitem_order_menuitem',
        ),
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='api_menuite_is_avai_8d19b9_idx',
            old_name='api_menuite_is_avail_b69ecd_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_status_dee4b6_idx',
            old_name='api_order_status_0d9a12_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='api_order_created_7fb22c_idx',
            old_name='api_order_created_66e0f5_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='api_orderit_order_i_3f9c70_idx',
            old_name='api_orderit_order_id_927e3b_idx',
        ),
        migrations.RenameIndex(
            model_name='orderstatusevent',
            new_name='api_orderst_order_i_9fbca8_idx',
            old_name='api_orderst_order_id_1d89bb_idx',
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'menu_item')},
        ),
    ]
